// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package cache

import (
	"database/sql"
	"time"
)

type PrayerTime struct {
	ID        int64
	City      string
	Date      time.Time
	Fajr      string
	Dhuhr     string
	Asr       string
	Maghrib   string
	Isha      string
	CreatedAt sql.NullTime
}
